name: Test Autocoder Action

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  run_autocoder:
    if: github.event.label.name == 'autocoder-bot'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Add this step here to satisfy the test requirements
      - name: Configure Git Credentials
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"

      - name: Call My Custom Action
        uses: ./ 
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SCRIPT_PATH: 'scripts/script.sh'
          LABEL: 'autocoder-bot'
